name: "sakura-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /logs/fastapi-elk-stack.*
  fields:
    - service: sakura_mini_admin
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "sakura-app"