# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases\requests.json
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseRequests(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(
            RunRequest("/get")
            .get("http://postman-echo.com/get")
            .with_params(**{"foo1": "bar1", "foo2": "bar2"})
            .with_headers(
                **{
                    "if-none-match": 'W/"452-ObnzKqac5ujm8LyNbDllw04To7E"',
                    "sec-ch-ua": '"Microsoft Edge";v="107", "Chromium";v="107", "Not=A?Brand";v="24"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                    "sec-fetch-dest": "document",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-site": "none",
                    "sec-fetch-user": "?1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.url", "http://postman-echo.com/get?foo1=bar1&foo2=bar2")
        ),
    ]


if __name__ == "__main__":
    TestCaseRequests().test_start()
