"""create user table

Revision ID: 785f5dc02533
Revises: 
Create Date: 2023-04-07 16:44:01.762156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785f5dc02533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
